version: 2
jobs:
  deploy:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
              - "d2:52:09:fa:ac:33:cd:ab:4b:9d:18:57:18:a7:3f:07"
      - run:
          name: ssh & deploy
          command: ssh ec2-user@18.181.209.134 'WorkLiveShift/deploy.sh'

workflows:
    version: 2
    build-deploy:
      jobs:
        - deploy:
            filters:
              branches:
                only: docker-yasuo
